package hackaton.cimarrones.com.xikin;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Created by Jonathan on 23/04/2017.
 */

public class ServicePalabras {

    public static List<String> getPalabras(){
        String[] cosas ={"a", "abajo",
                "abril",
                "abrir",
                "abuela",
                "abuelo",
                "aceptar",
                "acompañado",
                "adentro",
                "adulto",
                "afuera",
                "agarrar",
                "agosto",
                "ahí",
                "ahijada",
                "ahijado",
                "ahora",
                "algo",
                "alto",
                "amable",
                "amante",
                "amiga",
                "amigo",
                "anciana",
                "anciano",
                "ante",
                "antes",
                "año",
                "aqui",
                "ayer",
                "ayudar",
                "b",
                "baja california",
                "bajar",
                "baño",
                "buenas noches",
                "buenas tardes",
                "buenos dias",
                "c",
                "cada",
                "calma",
                "caminar",
                "cerrar",
                "certificado",
                "cierto",
                "compas",
                "con",
                "conmigo",
                "contestar",
                "contigo",
                "contra",
                "corredor",
                "corto",
                "cual",
                "d",
                "dar",
                "de",
                "debajo",
                "defender",
                "dejar",
                "delante",
                "derecha",
                "despacio",
                "despues",
                "detener",
                "detras",
                "dia",
                "diciembre",
                "diferente",
                "dificil",
                "domingo",
                "duda",
                "e",
                "el-ella",
                "ellos",
                "empezar",
                "en",
                "encontrar",
                "enero",
                "entrar",
                "entre",
                "entregar",
                "esa/ese/eso",
                "escoger",
                "f",
                "familia",
                "favor",
                "febrero",
                "femenino",
                "frontera",
                "g",
                "grande",
                "gratis",
                "guardar",
                "h",
                "hacer",
                "hermana",
                "hermano",
                "hija",
                "hijastra",
                "hijo",
                "hombre",
                "hoy",
                "i",
                "izquierda", "j", "jamas", "joven"};
        return Arrays.asList(cosas);
    }
}
